import type { Metadata } from "next";
import Link from "next/link";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import {AppBar, Toolbar, Typography, Button, Box} from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';

import theme from '../theme';
import './layout.css'

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//style={{background:"#525c54"}}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          {/* AppBar is added to layout so it is shared among all pages */}
          <ThemeProvider theme={theme}>
            <AppBar elevation={0}> 
              <Toolbar>
                <Typography 
                  variant="h3" 
                  component={Link}
                  href="/"
                  sx={{  flexGrow: 1, fontWeight: 'bold'}}>
                    Uche<span style={{color: "#990000"}}>Dev</span>
                </Typography>
                <Button 
                size="large">
                {/**TODO: Add linking for Projects page */}
                    Projects
                </Button>
                <Button 
                  size="large"
                  href="/blogs"
                  LinkComponent={Link}>
                    Blogs
                </Button>
              </Toolbar>
            </AppBar>
            {/* Empty toolbar is added add spacing between AppBar and website contents */}
            <Toolbar />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
