import type { Metadata } from "next";
import Link from "next/link";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import {AppBar, Toolbar, Typography, Button, Box} from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{background:"#525c54"}}>
        <AppRouterCacheProvider>

          {/* AppBar is added to layout so it is shared among all pages */}
          <ThemeProvider theme={theme}>
            <AppBar sx={{background: "#7D8C80", p:0}} elevation={0}> 
              <Toolbar>
                <Typography 
                  variant="h3" 
                  component={Link}
                  href="/"
                  
                  sx={{ textDecoration: 'none', flexGrow: 1, fontWeight: 'bold',
                  '&:visited': {
                    color: 'inherit'
                  }
                   }}>
                    UcheDev
                </Typography>
                <Button 
                color="inherit" 
                size="large"
                href="/projects"
                LinkComponent={Link}
                sx={{
                  m:0,
                  '&:hover': {
                  backgroundColor: '#990000',
                  boxShadow: 'none',
                }}}>
                    Projects
                </Button>
                <Button 
                  color="inherit" 
                  size="large"
                  href="/blogs"
                  LinkComponent={Link}
                  sx={{'&:hover': {
                    backgroundColor: '#990000',
                    boxShadow: 'none',
                  }}}>
                    Blogs
                </Button>
              </Toolbar>
            </AppBar>
            {/* Empty toolbar is added add spacing between AppBar and website contents */}
            <Toolbar />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
